page_manager.page.*:
  type: mapping
  label: 'Page'
  mapping:
    id:
      type: string
      label: 'Machine-readable name'
    label:
      type: label
      label: 'Label'
    uuid:
      type: string
      label: 'UUID'
    status:
      type: boolean
      label: 'Enabled status of the configuration entity'
    langcode:
      type: string
      label: 'Default language'
    path:
      type: string
      label: 'Page path'
    page_variants:
      type: sequence
      label: 'Page Variants'
      sequence:
        - type: page_manager.page_variant.[id]
          label: 'Page Variant'
    access_logic:
      type: string
      label: 'Access logic'
    access_conditions:
      type: sequence
      label: 'Access Conditions'
      sequence:
        - type: page_manager.access_condition
          label: 'Access Condition'
    dependencies:
      type: config_dependencies
      label: 'Dependencies'

page_manager.page_variant:
  type: mapping
  label: 'Page Variant'
  mapping:
    id:
      type: string
      label: 'ID'
    label:
      type: label
      label: 'Label'
    weight:
      type: integer
      label: 'Weight'
    uuid:
      type: string
      label: 'UUID'

page_manager.page_variant.block_page:
  type: page_manager.page_variant
  label: 'Block page variant'

page_manager.page_variant.http_status_code:
  type: page_manager.page_variant
  label: 'HTTP status code page variant'

page_manager.access_condition:
  type: mapping
  label: 'Access Condition'
  mapping:
    id:
      type: string
      label: 'ID'
    negate:
      type: boolean
      label: 'Negate'
    uuid:
      type: string
      label: 'UUID'
